### ISSUE TITLE
How to find passwords for `homeassistant` or `addons` users?

### ISSUE THREAD

**Issue by mahnunchik** [hassio-addons/addon-mqtt-io#132]
# Problem/Motivation

https://github.com/home-assistant/addons/blob/master/mosquitto/DOCS.md#home-assistant-user-management

According to the documentation `homeassistant` and `addons` users are pre-registered. I'd like to use `mqtt-io` addon with Mosquitto broker. Since this is an **addon**, it makes sense to use the existing `addons` user for it.

How to find passwords for `homeassistant` or at least `addons` user?

Maybe there is some predefined user/pass that can be used in mqtt-io config?

/homeassistant/mqtt-io/config.yml
```yml
mqtt:
  host: homeassistant.local
  topic_prefix: mqtt_io
  user: homeassistant #OR addons
  password: #?????????????????
  ha_discovery:
    enabled: yes
```

## Expected behavior

It should be possible to find password for `addons` user to specify it in addon config.

## Actual behavior

I couldn't find the password.

## Steps to reproduce

1. Install Mosquitto broker
2. Install MQTT IO
3. I'm shocked that the addon can't connect...
