### ISSUE TITLE
Add support for environment variables

### ISSUE THREAD

**Issue by pmgledhill102** [hassio-addons/addon-mqtt-io#19]
# Problem/Motivation

I have the plug-in working. But I have to hard-code a user-name and password into the config file.

I would like to be able to hook into the Services API to retrieve connection details, so I can remove these sensitive details

For example:

```yaml
mqtt:
  host: core-mosquitto
  user: mosquitto
  password: XeEb8
  topic_prefix: /home/alarm
  ha_discovery:
    enabled: true
```

## Expected behaviour

I would like to be able to use placeholders for the MQTT server, username and password. Such as:

```yaml
mqtt:
  host: { { my_env('MQTT_HOST') } }
  user: { { my_env('MQTT_USER') } }
  password: { { my_env('MQTT_PASSWORD') } }
  topic_prefix: /home/alarm
  ha_discovery:
    enabled: true
```

## Proposed changes

I have mqtt-io working with environment variables in my own environment. To make this work I needed to...

Create a static render.yaml file with the contents:

```yaml
backends:
  my_env:
    type: env
```

This tells mqtt-io that you want to define a config source called `my_env` and it should use the `env` backend add-in.

I then add a parameter when the python is started...

```sh
python3 -m mqtt_io --render render.yaml config.yaml
```

so in this context, I think the `mqtt-io/rootfs/etc/services.d/mqtt-io/run` file needs updating to include:

```sh
MQTT_HOST=$(bashio::services mqtt "host")
MQTT_USER=$(bashio::services mqtt "username")
MQTT_PASSWORD=$(bashio::services mqtt "password")

exec python3 -m mqtt_io --render render.yaml "$(bashio::config 'configuration_file')"
```

and the `mqtt-io/config.yaml` file would need updating to include the mqtt service

```yaml
services:
  - mqtt:need
```

I can try and get this working myself - but I wanted to raise as an issue to ensure this is a good approach given your much greater experience with the HAOS platform
